buttons_size: 32
additional_html: "<a class=\"a2a_button_facebook\"></a>\r\n<a class=\"a2a_button_twitter\"></a>\r\n<a class=\"a2a_button_facebook_messenger\"></a>\r\n<a class=\"a2a_button_line\"></a>\r\n<a class=\"a2a_button_copy_link\"></a>\r\n<a class=\"a2a_button_skype\"></a>"
additional_css: ''
additional_js: ''
universal_button: none
custom_universal_button: ''
universal_button_placement: before
no_3p: false
entities:
  media: 1
  node: 0
  comment: 0
  block_content: 0
  commerce_log: 0
  commerce_order: 0
  commerce_order_item: 0
  commerce_payment: 0
  commerce_payment_method: 0
  commerce_product: 1
  commerce_product_attribute_value: 0
  commerce_product_variation: 0
  commerce_promotion_coupon: 0
  commerce_promotion: 0
  commerce_shipment: 0
  commerce_shipping_method: 0
  commerce_stock_location: 0
  commerce_store: 0
  commerce_wishlist: 0
  commerce_wishlist_item: 0
  contact_message: 0
  file: 0
  legal_accepted: 0
  legal_conditions: 0
  profile: 0
  search_api_task: 0
  shortcut: 0
  taxonomy_term: 0
  user: 0
  webform_submission: 0
  menu_link_content: 0
_core:
  default_config_hash: 9YPlBuinIKLe5jVEf-aIhZvKFn77i18yD4CrNR0BbVQ
