key.provider.pubkey_encrypt:
  type: mapping
  label: 'Pubkey Encrypt key provider settings'
  mapping:
    role:
     type: string
     label: 'Role name'
    share_keys:
      type: sequence
      label: 'Share keys'
      sequence:
        type: string
        label: 'Share key for a specific user'
