pubkey_encrypt.initialization_settings:
  type: config_object
  label: 'Pubkey Encrypt Initialization Settings'
  mapping:
    module_initialized:
      type: boolean
      label: 'Tells whether the module has been initialized or not.'
    asymmetric_keys_generator:
      type: string
      label: 'Stores the reference to asymmetric keys generator plugin.'
    asymmetric_keys_generator_configuration:
      type: asymmetric_keys_generator.configuration.[%parent.asymmetric_keys_generator]
      label: 'Asymmetric keys generator plugin configuration'
    login_credentials_provider:
      type: string
      label: 'Stores the reference to login credentials provider plugin.'

asymmetric_keys_generator.configuration.*:
  type: sequence
  label: 'asymmetric keys generator plugin configuration.'
  sequence:
    type: string

pubkey_encrypt.admin_settings:
  type: config_object
  label: 'Pubkey Encrypt Settings'
  mapping:
    enabled_roles:
      type: sequence
      label: 'Enabled roles.'
      sequence:
        type: string
