commerce_amazon_lpa_merchant_account:
  type: mapping
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    mws_access_key:
      type: string
      label: 'MWS Access Key'
    mws_secret_key:
      type: string
      label: 'MWS Secret Key'
    lwa_client_id:
      type: string
      label: 'LWA Client ID'
    region:
      type: string
      label: 'Region'
    langcode:
      type: string
      label: 'Language code'

commerce_amazon_lpa_button_appearance:
  type: mapping
  mapping:
    size:
      type: string
      label: 'Size'
    style:
      type: style
      label: 'Style'

commerce_amazon_lpa.settings:
  type: config_entity
  mapping:
    operation_mode:
      type: string
      label: 'Operation mode'
    mode:
      type: string
      label: 'Mode'
    role_access:
      type: sequence
      sequence:
        type: string
    use_popup:
      type: boolean
      label: 'Use popup or redirect'
    authorization_mode:
      type: string
      label: 'Authorization mode'
    capture_mode:
      type: string
      label: 'Capture mode'
    auth_statement:
      type: string
      label: 'Authorization statement'
    buttons:
      type: mapping
      label: 'Button configuration'
      mapping:
        pay:
          type: commerce_amazon_lpa_button_appearance
          label: 'Pay button'
        login:
          type: commerce_amazon_lpa_button_appearance
          label: 'Login button'
    logging:
      type: boolean
      label: 'Enable logging'
    simulation_mode:
      type: string
      label: 'Sandbox simulation'
    merchant_information:
      type: sequence
      sequence:
        type: commerce_amazon_lpa_merchant_account

commerce_checkout.commerce_checkout_flow.plugin.amazon_pay:
  type: mapping
  mapping:
    display_checkout_progress:
      type: boolean
      label: 'Display checkout progress'
    require_shipping_profile:
      type: boolean
      label: 'Hide shipping costs until an address is entered'
    coupons:
      type: integer
      label: 'Allow coupons'
